'📚 documentation':
  - any: ['docs/**', '!docs/**/package.json']

'🌀 cli':
  - any: ['cli/**', '!cli/**/package.json']

'apps':
  - any: ['apps/**', '!apps/**/package.json']

'@coursebuilder/ui':
  - any: [ 'packages/ui/**', '!packages/ui/package.json' ]

'@coursebuilder/core':
  - any: [ 'packages/core/**', '!packages/core/package.json' ]

'@coursebuilder/next':
  - any: [ 'packages/next/**', '!packages/next/package.json' ]

'@coursebuilder/adapter-drizzle':
  - any: [ 'packages/adapter-drizzle/**', '!packages/adapter-drizzle/package.json' ]
