name: 'Setup and install'
description: 'Common setup steps for Actions'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Setup bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - shell: bash
      run: pnpm install

    - name: Copy .env.example files
      shell: bash
      run:
        find ./apps -type f -name ".env.example" -exec sh -c 'cp "$1"
        "${1%.example}"' _ {} \;
