import { createEnv } from '@t3-oss/env-core'
import { z } from 'zod'

export const env = createEnv({
	server: {
		STRIPE_SECRET_TOKEN: z.string().optional(),
		STRIPE_WEBHOOK_SECRET: z.string().optional(),
		COURSEBUILDER_URL: z.preprocess(
			(str) =>
				process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : str,
			z.string().optional(),
		),
		DATABASE_URL: z
			.string()
			.url()
			.refine(
				(str) => !str.includes('YOUR_MYSQL_URL_HERE'),
				'You forgot to change the default URL',
			),
		NODE_ENV: z
			.enum(['development', 'test', 'production'])
			.default('development'),
		OPENAI_API_KEY: z.string().optional(),
		REPLICATE_API_KEY: z.string().optional(),
		ANTHROPIC_API_KEY: z.string().optional(),
		INNGEST_EVENT_KEY: z.string().optional(),
		INNGEST_SIGNING_KEY: z.string().optional(),
		MUX_SECRET_KEY: z.string().optional(),
		MUX_ACCESS_TOKEN_ID: z.string().optional(),
		OPENAI_MODEL_ID: z.string().optional(),
		UPSTASH_REDIS_REST_URL: z.string().optional(),
		UPSTASH_REDIS_REST_TOKEN: z.string().optional(),
		DEEPGRAM_API_KEY: z.string().optional(),
		UPLOADTHING_URL: z.string().optional(),
		POSTMARK_API_KEY: z.string().optional(),
		POSTMARK_WEBHOOK_SECRET: z.string().optional(),
		GITHUB_CLIENT_ID: z.string().optional(),
		GITHUB_CLIENT_SECRET: z.string().optional(),
		TWITTER_CLIENT_ID: z.string().optional(),
		TWITTER_CLIENT_SECRET: z.string().optional(),
		RESEND_API_KEY: z.string().optional(),
		AWS_REGION: z.string().optional(),
		AWS_ACCESS_KEY_ID: z.string().optional(),
		AWS_SECRET_ACCESS_KEY: z.string().optional(),
		AWS_BUCKET_NAME: z.string().optional(),
		CONVERTKIT_API_SECRET: z.string().optional(),
		CONVERTKIT_API_KEY: z.string().optional(),
		CONVERTKIT_SIGNUP_FORM: z.union([z.string(), z.number()]).optional(),
		EMAIL_SERVER_HOST: z.string().optional(),
		EMAIL_SERVER_PORT: z.coerce.number().optional(),
		POSTMARK_KEY: z.string().optional(),
		SLACK_TOKEN: z.string().optional(),
		SLACK_DEFAULT_CHANNEL_ID: z.string().optional(),
		DISCORD_CLIENT_SECRET: z.string().optional(),
		DISCORD_BOT_TOKEN: z.string().optional(),
		DISCORD_GUILD_ID: z.string().optional(),
		DISCORD_MEMBER_ROLE_ID: z.string().optional(),
		DISCORD_CLIENT_ID: z.string().optional(),
	},

	client: {
		PUBLIC_APP_NAME: z.string().optional(),
		PUBLIC_GOOGLE_ANALYTICS: z.string().optional(),
		PUBLIC_PARTYKIT_ROOM_NAME: z.string().optional(),
		PUBLIC_PARTY_KIT_URL: z.string().optional(),
		PUBLIC_URL: z.string().optional(),
		PUBLIC_CLOUDINARY_CLOUD_NAME: z.string().optional(),
		PUBLIC_CLOUDINARY_UPLOAD_PRESET: z.string().optional(),
		PUBLIC_AMPLITUDE_API_KEY: z.string().optional(),
		PUBLIC_SUPPORT_EMAIL: z.string().optional(),
		PUBLIC_SITE_TITLE: z.string().optional(),
		PUBLIC_DISCORD_INVITE_URL: z.string().optional(),
	},

	runtimeEnv: {
		// Server vars
		STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
		STRIPE_SECRET_TOKEN: process.env.STRIPE_SECRET_TOKEN,
		COURSEBUILDER_URL: process.env.COURSEBUILDER_URL,
		DATABASE_URL: process.env.DATABASE_URL,
		NODE_ENV: process.env.NODE_ENV,
		REPLICATE_API_KEY: process.env.REPLICATE_API_KEY,
		ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
		OPENAI_API_KEY: process.env.OPENAI_API_KEY,
		OPENAI_MODEL_ID: process.env.OPENAI_MODEL_ID,
		INNGEST_EVENT_KEY: process.env.INNGEST_EVENT_KEY,
		INNGEST_SIGNING_KEY: process.env.INNGEST_SIGNING_KEY,
		MUX_ACCESS_TOKEN_ID: process.env.MUX_ACCESS_TOKEN_ID,
		MUX_SECRET_KEY: process.env.MUX_SECRET_KEY,
		GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
		GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
		DEEPGRAM_API_KEY: process.env.DEEPGRAM_API_KEY,
		UPLOADTHING_URL: process.env.UPLOADTHING_URL,
		POSTMARK_API_KEY: process.env.POSTMARK_API_KEY,
		POSTMARK_WEBHOOK_SECRET: process.env.POSTMARK_WEBHOOK_SECRET,
		TWITTER_CLIENT_ID: process.env.TWITTER_CLIENT_ID,
		TWITTER_CLIENT_SECRET: process.env.TWITTER_CLIENT_SECRET,
		UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
		UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
		RESEND_API_KEY: process.env.RESEND_API_KEY,
		AWS_REGION: process.env.AWS_REGION,
		AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
		AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
		AWS_BUCKET_NAME: process.env.AWS_BUCKET_NAME,
		CONVERTKIT_API_SECRET: process.env.CONVERTKIT_API_SECRET,
		CONVERTKIT_API_KEY: process.env.CONVERTKIT_API_KEY,
		CONVERTKIT_SIGNUP_FORM: process.env.CONVERTKIT_SIGNUP_FORM,
		EMAIL_SERVER_HOST: process.env.EMAIL_SERVER_HOST,
		EMAIL_SERVER_PORT: process.env.EMAIL_SERVER_PORT,
		POSTMARK_KEY: process.env.POSTMARK_KEY,
		SLACK_TOKEN: process.env.SLACK_TOKEN,
		SLACK_DEFAULT_CHANNEL_ID: process.env.SLACK_DEFAULT_CHANNEL_ID,
		DISCORD_CLIENT_ID: process.env.DISCORD_CLIENT_ID,
		DISCORD_CLIENT_SECRET: process.env.DISCORD_CLIENT_SECRET,
		DISCORD_BOT_TOKEN: process.env.DISCORD_BOT_TOKEN,
		DISCORD_GUILD_ID: process.env.DISCORD_GUILD_ID,
		DISCORD_MEMBER_ROLE_ID: process.env.DISCORD_MEMBER_ROLE_ID,

		// Client vars
		PUBLIC_APP_NAME: process.env.PUBLIC_APP_NAME,
		PUBLIC_GOOGLE_ANALYTICS: process.env.PUBLIC_GOOGLE_ANALYTICS,
		PUBLIC_PARTYKIT_ROOM_NAME: process.env.PUBLIC_PARTYKIT_ROOM_NAME,
		PUBLIC_PARTY_KIT_URL: process.env.PUBLIC_PARTY_KIT_URL,
		PUBLIC_URL: process.env.PUBLIC_URL,
		PUBLIC_CLOUDINARY_CLOUD_NAME: process.env.PUBLIC_CLOUDINARY_CLOUD_NAME,
		PUBLIC_CLOUDINARY_UPLOAD_PRESET:
			process.env.PUBLIC_CLOUDINARY_UPLOAD_PRESET,
		PUBLIC_AMPLITUDE_API_KEY: process.env.PUBLIC_AMPLITUDE_API_KEY,
		PUBLIC_SUPPORT_EMAIL: process.env.PUBLIC_SUPPORT_EMAIL,
		PUBLIC_SITE_TITLE: process.env.PUBLIC_SITE_TITLE,
		PUBLIC_DISCORD_INVITE_URL: process.env.PUBLIC_DISCORD_INVITE_URL,
	},

	skipValidation: !!process.env.SKIP_ENV_VALIDATION,
	emptyStringAsUndefined: true,
})
