export const titles = ["Refactor JSX in React to Stateless Functional Components",
"Render in React Based on a Global State Object",
"Load Data Based on Angular Route Params",
"Apply Natural Transformations in everyday work",
"Return Multiple Values from Observables in RxJS",
"Filter Data on Property Values in React",
"Push Values from Observables in RxJS",
"Refactoring mutations to enforce immutable data in Angular 2",
"Use Some as a Ternary Operator or Conditional",
"Select From Multiple Nested Angular 2 Elements",
"Throw Errors with RxJS Observables",
"Check ngModel Validation in Angular 2",
"Understand Angular @Injectable",
"Write an Angular Directive",
"Changing Behavior with MapTo",
"Combining Streams with CombineLatest",
"Understand OpaqueToken in Angular",
"Understand the Angular Base href Requirement",
"Use an Android library in NativeScript for Angular using Java apis",
"Redux: Normalizing API Responses with normalizr",
"Create a List of Items with a React Native ListView",
"Use Angular Factory Providers with dependencies",
"Understand Scope in Python",
"Use Provide and UseClass in Angular Providers",
"Use a Reducer to Change an Object's Property Inside an Array",
"Refactoring Composable Streams in RxJS",
"Parenting in GIF Loop Coder",
"Create a Generic Cycle.js Component",
"Use RxJS Streams with Angular 2 Forms",
"angular-formly: expressionProperties",
"Better Code Organization with selection.call() with D3 v4",
"Displaying Initial Data with StartWith",
"Advanced Console Log Arguments",
"Save and Delete Content in Express with HTTP Verbs",
"Render on the DOM with RxJS",
"Getting Input Text with Map",
"An overview of RxJS reactive concepts",
"Translate common Java/Android APIs into NativeScript for Angular Android apps",
"Use Objective C Delegates in NativeScript for Angular iOS apps",
"Ensure failsafe combination using monoids",
"Reuse Code in Multiple Projects with Python Modules",
"Reuse Styles with the SCSS @mixin Directive",
"Redux: Fetching Data on Route Change",
"Load Data to Build Angular Navigation",
"Make D3 v4 Charts Responsive with the viewBox attribute",
"Use RxJS Async Requests and Responses",
"Use SCSS Variables for Readable and Maintainable Stylesheets",
"Use Streams in Express",
"Split an RxJS Observable into Groups with groupBy",
"Organize Styles with SCSS Nesting and the Parent Selector",
"Transpile SCSS to CSS using node-sass",
"angular-formly: Default Values",
"Manage packages with pip in Python",
"angular-formly: Custom Validation",
"Organize SCSS into Multiple Files with Partials",
"Sync the UI with the app state using MobX observable and observer in React",
"Use Python Classes",
"Grouping and Nesting Console Log Output",
"Angular Material: Containers with the Layout API",
"Default Values for Function Parameters in ES6",
"Pass observable data through props in MobX",
"Use MobX actions to change and guard state",
"Using the ES6 spread operator",
"Send new requests from refresh clicks in RxJS",
"Reuse Styles with the SCSS @extend Directive",
"Angular Material: Theming and ARIA",
"Convert RxJS Subjects to Observables",
"Refactor Angular Controller Logic to Services",
"Replace Observable.create with Observable creation helpers",
"Export Values from Components through Sinks in Cycle.js",
"Develop a consistent plugin api across your Android and iOS NativeScript app",
"Derive computed values and manage side effects with MobX reactions",
"Perform an Action on Completion withRxJS Observables",
"Use takeUntil instead of manually unsubscribing from Observables",
"Write similar classes with the SCSS @for Control Directive",
"Add color to graphics using HTML Canvas",
"Deliver Synchronous Values with the RxJS of() Operator",
"Serve static files with express",
"Overview of Cycle.js",
"Yarn: A JavaScript Package Manager",
"Convert an underlying source of data into an Observable",
"Loop Over Data with the SCSS @each Control Directive",
"Animate with the General Update Pattern in D3 v4",
"Organize Code by Subpath in Express",
"Delay Evaluation with LazyBox",
"Using React with the FullCalendar jQuery plugin",
"Sum of the most common algorithmic arithmetic series",
"Handle user input and asynchronous actions with MobX",
"Render lists of data in Vue with v-for",
"Use the map operator instead of firing events on a Subject",
"Connect MobX observer components to the store with the React Provider",
"Allocate Dynamic Memory in WebAssembly with Malloc",
"Write Custom Functions with the SCSS @function Directive",
"Reduce an Array into a Single Object",
"Write custom MobX reactions with when and autorun",
"Use flattening operators instead of nested subscriptions",
"Convert JavaScript Values to RxJS Observables",
"Build a select dropdown with *ngFor in Angular 2",
"Transform an Array into a Single Value using Reduce",
"Redux: The Reducer Function",
"Redux: The Middleware Chain",
"Use switchMap to avoid leaks when flattening",
"Use Reduce to Filter and Map over Large Datasets",
"Find the intersection of sets with Semigroups",
"Move important side effects from do() to subscribe()",
"Know when to extend the Observable class",
"Implement pause and resume feature correctly through RxJS",
"Convert DOM and Node.js Streams to RxJS Observables with fromEvent",
"Use Standard Built-in SCSS Functions for Common Operations:",
"Create a custom npm script",
"An Observable execution may only have one Observer",
"Build 3D Panorama Scenes Using the Pano Component in React VR",
"Modify Values in an Array with Map",
"Subject: an Observable and Observer hybrid",
"BehaviorSubject: representing a value over time",
"NW.js and Webpack: A match made in heaven",
"Angular 2 Smart Components vs Presentation Components",
"ReplaySubject: remembering events from the past",
"Multicasting shortcuts: publish() and variants",
"Serving static files with hapi.js",
"Automatically Releasing with TravisCI",
"AsyncSubject: representing a computation that yields a final value",
"Refactor imperative code to a single composed expression using Box",
"Stopping a shared observable execution",
"Redux: Writing a Todo List Reducer (Adding a Todo)",
"Animate Colors with React Native Interpolate",
"Find Patterns at the Start and End of Lines with Line Anchors in Regular Expressions",
"Reusable multicasting with Subject factories",
"Automatically running tests before commits with ghooks",
"Animate Rotation with React Native Interpolate",
"Multicast with a selector argument, as a sandbox",
"Create a Flip Card Animation with React Native",
"Nesting Elements in Angular 2 Components with ng-content (AKA Angular 2 Transclusion)",
"Animate Multiple Animations at the Same Time with Animated.parallel",
"Find the Start and End of Words with Regular Expression Word Boundaries",
"Pass arguments to npm scripts",
"Use Angular style encapsulation to avoid styles from leaking into other components",
"Create a node script to replace a complex npm script",
"Display Validation and Error Messaging in Angular 2",
"Adding code coverage recording with Istanbul",
"The Factory Pattern for Javascript Modules",
"Use custom config settings in your npm scripts",
"Angular 1.x Redux: Integrate ngRedux",
"Use Sublime Text Snippets to Avoid Repetitive Typing",
"Consuming events as Observables in Angular 2",
"Proxy Requests for Local and Remote Service Parity",
"React components in ES6 classes",
"Create an API with Swagger",
"Learn to Flatten and Flatmap Arrays with Reduce",
"Introducing Angular 2 Concepts in Angular 1",
"Prepare for native iOS and Android api intellisense with NativeScript",
"Add styles to a component in Angular",
"Adding ES6 Support to Tests using Mocha and Babel",
"Define an HTTP GET Endpoint with URL Parameters for a Node.js Server with Swagger",
"Redux: Avoiding Object Mutations with Object.assign() and ...spread",
"Redux: Writing a Todo List Reducer (Toggling a Todo)",
"Create An API Schema Definition Using Swagger",
"Avoid Common Mistakes when Working with Reduce",
"Find the roots of words using stemming in Natural",
"Moving around in Vim",
"Define an HTTP GET Endpoint for a Node.js API Server with Swagger",
"Pluralizing nouns and counting numbers with inflectors in Natural",
"Create a Node.js function for an HTTP DELETE request for a Swagger API",
"Find sequences of words (n-grams) using Natural",
"Compare similarity of strings through string distance in Natural",
"Generate Angular 2 Components Programmatically with entryComponents",
"Define an HTTP DELETE Endpoint for a Node.js API Server with Swagger",
"Define Functional Components in Preact",
"Restrict null and undefined via Non-Nullable-Types in TypeScript",
"Show an Animated Buffering Icon When Remote Videos are Loading in React Native",
"Define Stateful Components in Preact",
"Read Input in Python from the Console",
"Setup React Native for iOS and Android",
"Define an HTTP POST Endpoint for a Node.js Server with Swagger",
"Catching errors with $exceptionHandler",
"Create Elements from Template Elements with ngTemplateOutlet in Angular",
"Use State and Props in the Component Render Function",
"Classify text into categories with machine learning in Natural",
"Responsive D3 charts with the viewBox attribute",
"Fetch non-JSON data by specifying HttpClient responseType in Angular",
"Compose Functions with Reduce",
"Create a Node.js function for an HTTP GET request for a Swagger API",
"Classify JSON text data with machine learning in Natural",
"Understand why Transducers can Improve Performance",
"Combine HostBinding with Services in Angular Directives",
"Define an HTTP PUT Endpoint for a Node.js API Server with Swagger",
"Clear data while loading with RxJS startWith",
"Examine AJAX Requests with Chrome Devtools",
"Debug D3 v4 with Dev Tools",
"Use Link State to Automatically Handle State Changes",
"Redux: Avoiding Array Mutations with concat(), slice(), and ...spread",
"Mock API Responses with Swagger",
"Build Monitoring into your API Server",
"Mock HTTP Requests made with Angular’s HttpClient in Unit Tests",
"Animate Transitions in D3 v4",
"Line and Area Charts with D3",
"Export Modules in Node.js",
"Search more efficiently with tries using Natural"]