export default {
	name: 'episode',
	type: 'document',
	title: 'Episode',
	groups: [
		{name: 'schedule', title: 'Schedule Details', default: true},
		{name: 'published', title: 'Published Details'},
	],
	fields: [
		{
			name: 'title',
			type: 'string',
			title: 'Title',
			group: 'schedule',
		},
		{
			title: 'Hide this episode on the website',
			name: 'hidden',
			type: 'boolean',
			options: {layout: 'checkbox'},
			group: 'schedule',
		},
		{
			name: 'slug',
			type: 'slug',
			title: 'Slug',
			description: 'What should the URL-friendly name of this episode be?',
			options: {
				source: 'title',
				maxLength: 96,
			},
			group: 'schedule',
		},
		{
			name: 'description',
			type: 'text',
			title: 'Episode Description',
			description: 'For Google SEO, previews, etc. — a brief overview.',
			group: 'schedule',
		},
		{
			name: 'date',
			type: 'datetime',
			title: 'Episode Date',
			group: 'schedule',
		},
		{
			name: 'guest',
			title: 'Guest(s)',
			type: 'array',
			of: [{type: 'reference', to: [{type: 'guest'}]}],
			group: 'schedule',
		},
		{
			name: 'host',
			title: 'Host',
			type: 'reference',
			to: [{type: 'guest'}],
			group: 'schedule',
		},
		{
			name: 'episodeTags',
			type: 'array',
			title: 'Tags',
			description:
				'Add tags so this episode shows up in grouped lists. When possible, stick to existing tags.',
			of: [{type: 'reference', to: [{type: 'episodeTag'}]}],
			group: 'schedule',
		},
		{
			name: 'youtubeID',
			type: 'string',
			title: 'YouTube ID',
			description: 'Just the ID, not the full URL.',
			group: 'published',
		},
		{
			name: 'demo',
			type: 'url',
			title: 'Demo URL',
			description: 'Where can people see the result of this episode online?',
			hidden: ({document}) => !document?.youtubeID,
			group: 'published',
		},
		{
			name: 'repo',
			type: 'url',
			title: 'Repo URL',
			description: 'Where can people see the source code?',
			hidden: ({document}) => !document?.youtubeID,
			group: 'published',
		},
		{
			name: 'links',
			type: 'array',
			title: 'Links and Resources',
			description: 'Links to anything that was mentioned during the episode.',
			of: [{type: 'url'}],
			hidden: ({document}) => !document?.youtubeID,
			group: 'published',
		},
		{
			title: 'Feature this episode',
			name: 'featured',
			type: 'boolean',
			options: {layout: 'checkbox'},
			hidden: ({document}) => !document?.youtubeID,
			group: 'published',
		},
		{
			name: 'transcript',
			type: 'markdown',
			title: 'Transcript',
			description: 'Get this from rev.com as a .txt file.',
			hidden: ({document}) => !document?.youtubeID,
			group: 'published',
		},
		{
			name: 'image',
			type: 'episodeImage',
			hidden: true,
		},
	],
	initialValue: () => ({
		host: {_type: 'reference', _ref: '1c607bb5-519b-49b6-9da9-5ddc424aa44c'},
		featured: false,
		hidden: false,
		image: {
			_type: 'episodeImage',
			alt: 'Learn With Jason',
			asset: {
				_ref: 'image-5b179f2cd1d20585ba62c631bc2400ca3643c0ae-1280x670-jpg',
				_type: 'reference',
			},
		},
	}),
}
