name: Apps E2E

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  e2e-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          [
            course-builder-web
          ]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install necessary deps
        run: pnpm --filter "./apps/${{ matrix.dir }}/**"  --filter "@coursebuilder/*" install

      - name: Setup
        uses: ./tooling/gh-actions/setup

      - name: Build Course Builder packages
        run: pnpm build --filter "@coursebuilder/*"

      - name: Run build
        run: pnpm turbo --filter ./apps/${{ matrix.dir }} build
